### PR TITLE
added direct login

### PR DESCRIPTION
**Pull request by avneesh0612**

### CODE REVIEW

**Comment by lorstenoplo** [comment]
Dude this error is comming : 
Failed to compile.
18:49:27  	./pages/doc/[id].tsx:28:25
18:49:27  	Type error: Property 'providers' is missing in type '{}' but required in type '{ providers: any; }'.
18:49:27  	  26 |   const classes = useStyles();
18:49:27  	  27 | 
18:49:27  	> 28 |   if (!session) return <Login />;
18:49:27  	     |                         ^
18:49:27  	  29 |   const [snapshot

**Comment by lorstenoplo** [comment]
@avneesh0612 please check and comment coz due to connection issues I'm not able use discord...

**Comment by avneesh0612** [comment]
Hello, @lorstenoplo I don't know typescript, So if you can merge it then add a type to providers it would be great!

**Comment by lorstenoplo** [comment]
Ok I'll do it tomorrow
Credits to internet issue for not able to merge today

**Comment by avneesh0612** [comment]
Ok @lorstenoplo

**Pull request merged**
